version: '3.9'
services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      TZ: America/Sao_Paulo
      ORACLE_PASSWORD: 123456
    ports:
      - 1522:1521
    expose:
      - 1522
    networks:
      - api-jwt

  spring-boot-app:
    build: .
    container_name: spring-boot-app
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1522:xe
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - 80:80
    depends_on:
      - oracle-db
    networks:
      - api-jwt

networks:
  api-jwt:
    driver: bridge