version: '3.9'
services:
  spring-boot-app:
    image: rick5678/spring-boot-app
    build: .
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@host.docker.internal:1521/xe
      SPRING_DATASOURCE_USERNAME: HENRIQUE
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - 8099:8099
    networks:
      - api-jwt

networks:
  api-jwt:
    driver: bridge